[versions]
fastjsonVersion  = "2.0.52"
hutool-allVersion  = "5.8.25"
pinyin4jVersion  = "2.5.1"
tomljVersion  = "1.1.1"
kotlin = "2.1.0+"
intellij = "+"
lsp4j = "0.23.1"
jimmer = "0.9.49"
shadow = "9.0.0-beta2"
jackson = "2.18.2"
asm = "9.7.1"
antlr = "4.13.2"
tomlj = "1.1.1"

[libraries]
com-alibaba-fastjson ={group="com.alibaba",name= "fastjson",version.ref="fastjsonVersion"}
cn-hutool-hutool-all ={group="cn.hutool",name= "hutool-all",version.ref="hutool-allVersion"}
com-belerweb-pinyin4j ={group="com.belerweb",name= "pinyin4j",version.ref="pinyin4jVersion"}
org-tomlj-tomlj ={group="org.tomlj",name= "tomlj",version.ref="tomljVersion"}
lsp4j = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j", version.ref = "lsp4j" }
jimmer-dtoCompiler = { module = "org.babyfish.jimmer:jimmer-dto-compiler", version.ref = "jimmer" }
jimmer-core = { module = "org.babyfish.jimmer:jimmer-core", version.ref = "jimmer" }
jimmer-coreKotlin = { module = "org.babyfish.jimmer:jimmer-core-kotlin", version.ref = "jimmer" }
jimmer-sql = { module = "org.babyfish.jimmer:jimmer-sql", version.ref = "jimmer" }
jimmer-sqlKotlin = { module = "org.babyfish.jimmer:jimmer-sql-kotlin", version.ref = "jimmer" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }
antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
intellij = { id = "org.jetbrains.intellij.platform", version.ref = "intellij" }
