[versions]
project = "1.0"
latest= "latest.release"
mysql = "8.0.29"
postgresql = "42.3.6"
aspose-words = "23.1"
commons-math = "3.6.1"
data-factory = "1.2.0"
easyexcel = "3.3.2"
fastjson = "2.0.31"
jakartaValidation = "3.0.2"
h2 = "2.2.224"
jdk = "22"
#jdk = "22"
jimmer = "0.9.0"
knife4j = "4.5.0"
junit = "5.10.0"  # 或者你使用的版本
minio = "8.5.7"
mybatis-plus = "3.5.4.1"
ortools = "9.10.4067"
poi = "5.2.5"
sa-token = "1.38.0"
spring-ai = "latest.release"
#spring-boot = "3.3.3"

spring-boot ="latest.release"

#spring-dependency-management = "1.1.6"
spring-dependency-management ="latest.release"
hutool = "5.8.28"
ksp = "2.0.20-1.0.25"

kotlin = "2.0.21"
lombok = "1.18.28"
mapstruct = "1.5.5.Final"
slf4j = "1.7.36"
pinyin-sdk = "8.1.7" # 新增的pinyin-sdk版本
aspectj = "1.9.22.1"
[libraries]
#编译时魔法
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }



# 数据库相关
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
jimmer = { group = "org.babyfish.jimmer", name = "jimmer-spring-boot-starter", version.ref = "jimmer" }
jimmer-ksp = { group = "org.babyfish.jimmer", name = "jimmer-ksp", version.ref = "jimmer" }
mysql-connector-java = { group = "mysql", name = "mysql-connector-java", version.ref = "mysql" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

# Spring 相关
spring-boot = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring-boot" }
spring-boot-dependencies = { group = "org.springframework.boot",name = "spring-boot-dependencies",version.ref = "spring-boot" }
spring-boot-configurationProcessor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-starter-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-jdbc", version.ref = "spring-boot" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux", version.ref = "spring-boot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
spring-data-jdbc = { group = "org.springframework.data", name = "spring-data-jdbc", version.ref = "spring-boot" }





# Spring AI 相关

spring-ai-bom = { group = "org.springframework.ai", name = "spring-ai-bom", version.ref = "spring-ai" }
spring-ai-pgvector-store = { group = "org.springframework.ai", name = "spring-ai-pgvector-store-spring-boot-starter", version.ref = "spring-ai" }
spring-ai-ollama = { group = "org.springframework.ai", name = "spring-ai-ollama-spring-boot-starter" , version.ref = "spring-ai"}
spring-ai-openai = { group = "org.springframework.ai", name = "spring-ai-openai-spring-boot-starter" , version.ref = "spring-ai"}
spring-ai-zhipuai = { group = "org.springframework.ai", name = "spring-ai-zhipuai-spring-boot-starter" , version.ref = "spring-ai"}
spring-ai-moonshot = { group = "org.springframework.ai", name = "spring-ai-moonshot-spring-boot-starter" , version.ref = "spring-ai"}
#spring-ai-alibaba = { group = "com.alibaba.cloud.ai", name = "spring-ai-alibaba-starter", version.ref = "spring-ai" }
spring-ai-alibaba = { group = "com.alibaba.cloud.ai", name = "spring-ai-alibaba-starter", version = "1.0.0-M2" }


spring-ai-tika = { group = "org.springframework.ai", name = "spring-ai-tika-document-reader" , version.ref = "spring-ai"}

# 通用工具
fastjson = { group = "com.alibaba.fastjson2", name = "fastjson2", version.ref = "fastjson" }
pinyin-sdk = { group = "cn.stylefeng.roses", name = "pinyin-sdk-pinyin4j", version.ref = "pinyin-sdk" }
sa-token = { group = "cn.dev33", name = "sa-token-spring-boot3-starter", version.ref = "sa-token" }

#office相关
easyexcel = { group = "com.alibaba", name = "easyexcel", version.ref = "easyexcel" }
aspose-words = { group = "com.luhuiguo", name = "aspose-words", version.ref = "aspose-words" }
#数学
commons-math = { group = "org.apache.commons", name = "commons-math3", version.ref = "commons-math" }
# mock数据
data-factory = { group = "com.github.houbb", name = "data-factory-core", version.ref = "data-factory" }
#openapi

knife4j = { group = "com.github.xiaoymin", name = "knife4j-openapi3-jakarta-spring-boot-starter", version.ref = "knife4j" }
hutool = { group = "cn.hutool", name = "hutool-all", version.ref = "hutool" }
minio = { group = "io.minio", name = "minio", version.ref = "minio" }
ortools = { group = "com.google.ortools", name = "ortools-java", version.ref = "ortools" }
poi = { group = "org.apache.poi", name = "poi", version.ref = "poi" }

aspectj = { group = "org.aspectj", name = "aspectjweaver" ,version.ref = "aspectj"}


mybatis-plus = { group = "com.baomidou", name = "mybatis-plus-boot-starter", version.ref = "mybatis-plus" }

jakarta-validation-api = { group = "jakarta.validation", name = "jakarta.validation-api", version.ref = "jakartaValidation" }
#jakartaee-api = { group = "jakarta.platform", name = "jakarta.jakartaee-api", version.ref = "jakartaee" }

#javax-validation-api = { group = "javax.validation", name = "validation-api", version.ref = "javaxValidation" }


# Kotlin 相关
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

[plugins]
#implementation 'org.jetbrains.kotlin:kotlin-noarg:2.1.0-Beta1'
kotlin-noarg = { id = "org.jetbrains.kotlin:kotlin-noarg", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }